site_name: Open Source LabVIEW Actions
site_url: https://labview-community-ci-cd.github.io/open-source/
repo_url: https://github.com/LabVIEW-Community-CI-CD/open-source
repo_name: open-source
edit_uri: edit/actions/docs/
site_description: Actions for automating LabVIEW workflows
site_author: Open Source Actions Team

docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - toc.integrate

markdown_extensions:
  - admonition
  - def_list
  - toc
  - pymdownx.superfences
  - pymdownx.highlight
nav:
  - Home:
    - Overview: index.md
    - Architecture: architecture.md
  - Quickstart: quickstart.md
  - Action Calls: action-call-reference.md
  - Common Parameters: common-parameters.md
  - Troubleshooting: troubleshooting.md
  - Unified Dispatcher: UnifiedDispatcher.md
  - Adapter Authoring: adapter-authoring.md
  - Versioning: versioning.md
  - Changelog: CHANGELOG.md
  - Contributing: contributing-docs.md
  - Requirements: requirements.md
  - Testing with Pester: testing-pester.md
  - Actions:
    - Add Token to LabVIEW: actions/add-token-to-labview.md
    - Apply VIPC: actions/apply-vipc.md
    - Build: actions/build.md
    - Build LVLIBP: actions/build-lvlibp.md
    - Build VI Package: actions/build-vi-package.md
    - Close LabVIEW: actions/close-labview.md
    - Generate Release Notes: actions/generate-release-notes.md
    - Missing in Project: actions/missing-in-project.md
    - Modify VIPB Display Info: actions/modify-vipb-display-info.md
    - Prepare LabVIEW Source: actions/prepare-labview-source.md
    - Rename File: actions/rename-file.md
    - Restore Setup LV Source: actions/restore-setup-lv-source.md
    - Revert Development Mode: actions/revert-development-mode.md
    - Run Unit Tests: actions/run-unit-tests.md
    - Set Development Mode: actions/set-development-mode.md
plugins:
  - search
  - autorefs
  - redirects:
      redirect_maps:
        old-page.md: new-page.md
