name: Build VI package (ubuntu test)

on:
  workflow_dispatch:

jobs:
  build-vi-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Run build-vi-package action
        uses: ./build-vi-package/action.yml
        with:
          minimum_supported_lv_version: '2021'
          supported_bitness: '64'
          labview_minor_revision: '0'
          relative_path: 'scripts/build-vi-package'
          vipb_path: 'scripts/build-vi-package/NI Icon editor.vipb'
          major: '1'
          minor: '0'
          patch: '0'
          build: '1'
          commit: 'abcdef'
          display_information_json: '{"Name":"Test"}'
          dry_run: true
      - name: Upload VI package
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: vi-package
          path: 'scripts/build-vi-package/lv_icon_v1.0.0.1+gabcdef.vip'
      - name: Generate SLSA provenance
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018
        with:
          subject-path: 'scripts/build-vi-package/lv_icon_v1.0.0.1+gabcdef.vip'
