name: Modify VIPB display info (ubuntu test)

on:
  workflow_dispatch:

jobs:
  modify-vipb-display-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Run modify-vipb-display-info action
        uses: ./modify-vipb-display-info/action.yml
        with:
          supported_bitness: '64'
          relative_path: 'scripts/modify-vipb-display-info'
          vipb_path: 'scripts/modify-vipb-display-info/lv_icon.vipb'
          minimum_supported_lv_version: '2021'
          labview_minor_revision: '0'
          major: '1'
          minor: '0'
          patch: '0'
          build: '1'
          commit: 'abcdef'
          display_information_json: '{"Name":"Test"}'
          dry_run: true
      - name: Upload vipb artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: vipb-display-info
          path: 'scripts/modify-vipb-display-info/lv_icon.vipb'
