name: Revert development mode (ubuntu test)

on:
  workflow_dispatch:

jobs:
  revert-development-mode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Run revert-development-mode action
        uses: ./revert-development-mode/action.yml
        with:
          relative_path: './'
      - name: Upload config artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: devmode-config
          path: 'devmode-config.txt'
